// study-vue/02/ResponseCheck.vue
<template>
    <div>
        <div id="screen" :class="state" @click="onClickScreen">{{message}}</div>
        <!-- v-show dom이 노출되어 있음 -->
        <!-- <div v-show="result.length">
            <div>평균 시간 : {{average}}ms</div>
            <button @click="onReset">리셋</button>
        </div> -->
        
        <!-- div가 싫다면 template -->
        <template v-if="result.length">
            <div>평균 시간 : {{average}}ms</div>
            <button @click="onReset">리셋</button>
        </template>
    </div>
</template>

<script>
    let startTime = 0;
    let endTime = 0;
    let timeout = null;
    export default {
        data() {
			return {
                result: [],
                state: 'waiting',
                message: '클릭해서 시작하세요.'
			};
        },
        computed:{ //매번 실행하지 않고 값이 변경이 될때 실행한다.(성능 최적화)
            average(){
                return this.result.reduce((a, c) => a + c, 0) / this.result.length || 0;
            }
        },
		methods: {
			onReset(){
                this.result = [];
            },
            onClickScreen(){
                if(this.state === 'waiting'){
                    this.state = 'ready';
                    this.message = '초록색이 되면 클릭하세요';
                    timeout = setTimeout(() => {
                        this.state = 'now';
                        this.message = '지금 클릭!';
                        startTime = new Date();
                    }, Math.floor(Math.random() * 1000) + 2000);
                }
                else if(this.state === 'ready'){
                    clearTimeout(timeout);
                    this.state = 'now';
                    this.message = '너무 성급하시군요! 초록색이 된 후에 클릭하세요.';
                }
                else if(this.state === 'now'){
                    endTime = new Date();
                    this.state = 'waiting';
                    this.message = '클릭해서 시작하세요';
                    this.result.push(endTime - startTime);
                }
            }
		}
    }
</script>

<style scoped>
#screen {width: 300px;height: 200px;text-align: center;user-select: none;}
#screen.waiting {background-color: aqua;}
#screen.ready {background-color: red;}
#screen.now {background-color:greenyellow;}

</style>

// study-react/react-webgame-master/4.반응속도체크2/ResponseCheck.jsx
import React, { useState, useRef } from 'react';

const ResponseCheck = () => {
  const [state, setstate] = useState('waiting');
  const [message, setMessage] = useState('클릭해서 시작하세요.');
  const [result, setResult] = useState([]);
  const timeout = useRef(null);
  const startTime = useRef(0);
  const endTime = useRef(0);

  const onClickScreen = () => {
    if(state === 'waiting'){
      timeout.current = setTimeout(()=>{
        setstate('now');
        setMessage('지금 클릭');
        startTime.current = new Date();
      }, Math.floor(Math.random() * 1000) + 2000);
      setstate('ready');
      setMessage('초록색이 되면 클릭하세요.');
    }
    else if(state === 'ready'){
      clearTimeout(timeout.current);
      setstate('waiting');
      setMessage('너무 성급하시군요! 초록색이 된 후에 클릭하세요.');
    }
    else if(state === 'now'){
      endTime.current = new Date();
      setstate('waiting');
      setMessage('클릭해서 시작하세요.');
      setResult(r=>([...r, endTime.current - startTime.current]));
    }
  };

  const onReset = () => {
    setResult([]);
  };

  const renderAverage = () => {
    return result.length === 0 
    ? null 
    : <>
        <div>평균 시간: {result.reduce((a,c)=>a+c) / result.length}ms</div>
        <button onClick={onReset}>리셋</button>
      </>
  };

  return (
    <>
      <div id="screen" className={state} onClick={onClickScreen}>
        {message}
      </div>
      {renderAverage()}
    </>
  );
};

export default ResponseCheck;
